// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsebmuinzspsaymozlek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzZWJtdWluenNwc2F5bW96bGVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDIxNzIsImV4cCI6MjA2NjI3ODE3Mn0.w8wOOXf5AONIFboNkLy-yZsT7m3txtc9F1AhA4iGh-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);